title: "CN Vocab - 中国語単語学習アプリ"
description: "HSKレベル別中国語語彙学習アプリ"
baseurl: ""
url: "https://misamoriii.github.io"

# GitHub Pages settings
include:
  - "README.md"
  - "privacy-policy.html"

# Exclude files
exclude:
  - "node_modules/"
  - "android/"
  - "ios/"
  - "src/"
  - "public/"
  - "*.js"
  - "*.json"
  - "*.md"
  - "*.ts"
  - "*.tsx"
  - "*.config.*"
  - "package*.json"